export type CountryDestinations = {
  name: string;
  countryCode: string;
  aliases: string[];
  cities: string[];
};

/** Países y ciudades principales para sugerencias en el asistente. */
export const DESTINATION_CATALOG: CountryDestinations[] = [
  {
    name: "Estados Unidos",
    countryCode: "US",
    aliases: ["usa", "eeuu", "ee uu", "united states", "us", "america"],
    cities: [
      "Nueva York",
      "Los Angeles",
      "Miami",
      "Las Vegas",
      "Chicago",
      "San Francisco",
      "Orlando",
      "Washington D. C.",
      "Boston",
      "Texas",
      "California",
      "Houston",
      "Seattle",
    ],
  },
  {
    name: "Argentina",
    countryCode: "AR",
    aliases: ["arg"],
    cities: [
      // Ciudades principales
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "La Plata",
      "Salta",
      "Bariloche",
      "Ushuaia",
      "Iguazú",
      "El Calafate",
      "Neuquén",
      "Mar del Plata",
      "Tucumán",
      "Santa Fe",
      "Paraná",
      "Posadas",
      "Resistencia",
      "Corrientes",
      "San Juan",
      "San Luis",
      "San Rafael",
      "Puerto Madryn",
      "Comodoro Rivadavia",
      "Río Gallegos",
      // Provincias (24 jurisdicciones)
      "Ciudad Autónoma de Buenos Aires",
      "Provincia de Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Misiones",
      "Río Negro",
      "Santa Cruz",
      "Santiago del Estero",
      "Tierra del Fuego",
      // Costa atlántica — Partido de la Costa y alrededores
      "Pinamar",
      "Cariló",
      "Ostende",
      "Valeriá",
      "Mar de las Pampas",
      "Villa Gesell",
      "Miramar",
      "San Clemente del Tuyú",
      "Santa Teresita",
      "San Bernardo",
      "Mar de Ajó",
      "Las Toninas",
      "Costa del Este",
      "San Cayetano",
      "Lucila del Mar",
      "Mar del Tuyú",
      "Aguas Verdes",
      "Necochea",
      "Claromecó",
      "Monte Hermoso",
      "Bahía Blanca",
      "Tandil",
      "Sierra de la Ventana",
      "Tigre",
      "San Antonio Oeste",
    ],
  },
  {
    name: "Brasil",
    countryCode: "BR",
    aliases: ["brazil"],
    cities: [
      "Río de Janeiro",
      "São Paulo",
      "Brasilia",
      "Salvador",
      "Florianópolis",
      "Fortaleza",
      "Recife",
      "Manaus",
      "Porto Alegre",
      "Buzios",
    ],
  },
  {
    name: "México",
    countryCode: "MX",
    aliases: ["mexico"],
    cities: [
      "Ciudad de México",
      "Cancún",
      "Playa del Carmen",
      "Guadalajara",
      "Monterrey",
      "Tulum",
      "Los Cabos",
      "Oaxaca",
      "Mérida",
      "Puerto Vallarta",
    ],
  },
  {
    name: "España",
    countryCode: "ES",
    aliases: ["spain"],
    cities: [
      "Madrid",
      "Barcelona",
      "Sevilla",
      "Valencia",
      "Málaga",
      "Ibiza",
      "Granada",
      "Bilbao",
      "Palma de Mallorca",
      "San Sebastián",
    ],
  },
  {
    name: "Francia",
    countryCode: "FR",
    aliases: ["france"],
    cities: ["París", "Niza", "Lyon", "Marsella", "Burdeos", "Estrasburgo", "Toulouse", "Montpellier"],
  },
  {
    name: "Italia",
    countryCode: "IT",
    aliases: ["italy"],
    cities: ["Roma", "Milán", "Venecia", "Florencia", "Nápoles", "Turín", "Bolonia", "Pisa", "Sicilia", "Amalfi"],
  },
  {
    name: "Reino Unido",
    countryCode: "GB",
    aliases: ["uk", "inglaterra", "england", "britain", "gran bretaña"],
    cities: ["Londres", "Edimburgo", "Manchester", "Liverpool", "Birmingham", "Glasgow", "Oxford", "Bristol"],
  },
  {
    name: "Alemania",
    countryCode: "DE",
    aliases: ["germany", "deutschland"],
    cities: ["Berlín", "Múnich", "Fráncfort", "Hamburgo", "Colonia", "Düsseldorf", "Stuttgart", "Dresde"],
  },
  {
    name: "Portugal",
    countryCode: "PT",
    aliases: [],
    cities: ["Lisboa", "Oporto", "Faro", "Coímbra", "Madeira", "Algarve", "Sintra", "Braga"],
  },
  {
    name: "Países Bajos",
    countryCode: "NL",
    aliases: ["holanda", "netherlands", "holland"],
    cities: ["Ámsterdam", "Rotterdam", "La Haya", "Utrecht", "Eindhoven", "Maastricht"],
  },
  {
    name: "Bélgica",
    countryCode: "BE",
    aliases: ["belgium"],
    cities: ["Bruselas", "Brujas", "Amberes", "Gante", "Lieja"],
  },
  {
    name: "Suiza",
    countryCode: "CH",
    aliases: ["switzerland", "swiss"],
    cities: ["Zúrich", "Ginebra", "Basilea", "Berna", "Lausana", "Lugano", "Interlaken"],
  },
  {
    name: "Austria",
    countryCode: "AT",
    aliases: [],
    cities: ["Viena", "Salzburgo", "Innsbruck", "Graz", "Linz"],
  },
  {
    name: "Grecia",
    countryCode: "GR",
    aliases: ["greece"],
    cities: ["Atenas", "Santorini", "Mykonos", "Creta", "Rodas", "Tesalónica", "Corfú"],
  },
  {
    name: "Turquía",
    countryCode: "TR",
    aliases: ["turkey", "turquia"],
    cities: ["Estambul", "Ankara", "Antalya", "Esmirna", "Capadocia", "Bodrum"],
  },
  {
    name: "Rusia",
    countryCode: "RU",
    aliases: ["russia"],
    cities: ["Moscú", "San Petersburgo", "Kazán", "Sochi", "Novosibirsk"],
  },
  {
    name: "Polonia",
    countryCode: "PL",
    aliases: ["poland"],
    cities: ["Varsovia", "Cracovia", "Gdansk", "Wroclaw", "Poznan"],
  },
  {
    name: "República Checa",
    countryCode: "CZ",
    aliases: ["chequia", "czech republic", "praga"],
    cities: ["Praga", "Brno", "Ostrava", "Karlovy Vary"],
  },
  {
    name: "Hungría",
    countryCode: "HU",
    aliases: ["hungary", "hungria"],
    cities: ["Budapest", "Debrecen", "Szeged", "Pécs"],
  },
  {
    name: "Croacia",
    countryCode: "HR",
    aliases: ["croatia"],
    cities: ["Zagreb", "Split", "Dubrovnik", "Zadar", "Hvar"],
  },
  {
    name: "Irlanda",
    countryCode: "IE",
    aliases: ["ireland"],
    cities: ["Dublín", "Cork", "Galway", "Limerick", "Killarney"],
  },
  {
    name: "Suecia",
    countryCode: "SE",
    aliases: ["sweden"],
    cities: ["Estocolmo", "Gotemburgo", "Malmö", "Upsala"],
  },
  {
    name: "Noruega",
    countryCode: "NO",
    aliases: ["norway"],
    cities: ["Oslo", "Bergen", "Trondheim", "Tromsø", "Stavanger"],
  },
  {
    name: "Dinamarca",
    countryCode: "DK",
    aliases: ["denmark"],
    cities: ["Copenhague", "Aarhus", "Odense", "Aalborg"],
  },
  {
    name: "Finlandia",
    countryCode: "FI",
    aliases: ["finland"],
    cities: ["Helsinki", "Tampere", "Turku", "Rovaniemi"],
  },
  {
    name: "Islandia",
    countryCode: "IS",
    aliases: ["iceland"],
    cities: ["Reikiavik", "Akureyri", "Keflavik"],
  },
  {
    name: "Rumania",
    countryCode: "RO",
    aliases: ["romania"],
    cities: ["Bucarest", "Cluj-Napoca", "Brașov", "Sibiu", "Timișoara"],
  },
  {
    name: "Bulgaria",
    countryCode: "BG",
    aliases: [],
    cities: ["Sofía", "Plovdiv", "Varna", "Burgas"],
  },
  {
    name: "Serbia",
    countryCode: "RS",
    aliases: [],
    cities: ["Belgrado", "Novi Sad", "Niš"],
  },
  {
    name: "Ucrania",
    countryCode: "UA",
    aliases: ["ukraine"],
    cities: ["Kiev", "Leópolis", "Odesa", "Jarkov", "Dnipro"],
  },
  {
    name: "Canadá",
    countryCode: "CA",
    aliases: ["canada"],
    cities: ["Toronto", "Montreal", "Vancouver", "Ottawa", "Calgary", "Quebec", "Whistler", "Banff"],
  },
  {
    name: "Chile",
    countryCode: "CL",
    aliases: [],
    cities: ["Santiago", "Valparaíso", "Viña del Mar", "San Pedro de Atacama", "Pucón", "Puerto Varas", "Punta Arenas"],
  },
  {
    name: "Colombia",
    countryCode: "CO",
    aliases: [],
    cities: ["Bogotá", "Medellín", "Cartagena", "Cali", "Barranquilla", "Santa Marta", "San Andrés", "Salento"],
  },
  {
    name: "Perú",
    countryCode: "PE",
    aliases: ["peru"],
    cities: ["Lima", "Cusco", "Arequipa", "Máncora", "Iquitos", "Puno", "Huacachina", "Trujillo"],
  },
  {
    name: "Ecuador",
    countryCode: "EC",
    aliases: [],
    cities: ["Quito", "Guayaquil", "Cuenca", "Galápagos", "Baños", "Manta"],
  },
  {
    name: "Bolivia",
    countryCode: "BO",
    aliases: [],
    cities: ["La Paz", "Santa Cruz", "Sucre", "Cochabamba", "Uyuni", "Potosí"],
  },
  {
    name: "Paraguay",
    countryCode: "PY",
    aliases: [],
    cities: ["Asunción", "Ciudad del Este", "Encarnación", "Filadelfia"],
  },
  {
    name: "Uruguay",
    countryCode: "UY",
    aliases: [],
    cities: ["Montevideo", "Punta del Este", "Colonia del Sacramento", "Piriápolis", "Salto"],
  },
  {
    name: "Venezuela",
    countryCode: "VE",
    aliases: [],
    cities: ["Caracas", "Margarita", "Mérida", "Maracaibo", "Los Roques"],
  },
  {
    name: "Costa Rica",
    countryCode: "CR",
    aliases: [],
    cities: ["San José", "La Fortuna", "Tamarindo", "Manuel Antonio", "Monteverde", "Limón"],
  },
  {
    name: "Panamá",
    countryCode: "PA",
    aliases: ["panama"],
    cities: ["Ciudad de Panamá", "Bocas del Toro", "Boquete", "San Blas", "Colón"],
  },
  {
    name: "Cuba",
    countryCode: "CU",
    aliases: [],
    cities: ["La Habana", "Varadero", "Trinidad", "Viñales", "Santiago de Cuba"],
  },
  {
    name: "República Dominicana",
    countryCode: "DO",
    aliases: ["dominicana", "rd"],
    cities: ["Punta Cana", "Santo Domingo", "Puerto Plata", "La Romana", "Samaná"],
  },
  {
    name: "Puerto Rico",
    countryCode: "PR",
    aliases: [],
    cities: ["San Juan", "Vieques", "Culebra", "Ponce", "Rincón"],
  },
  {
    name: "Jamaica",
    countryCode: "JM",
    aliases: [],
    cities: ["Kingston", "Montego Bay", "Negril", "Ocho Ríos"],
  },
  {
    name: "Guatemala",
    countryCode: "GT",
    aliases: [],
    cities: ["Ciudad de Guatemala", "Antigua", "Flores", "Lake Atitlán", "Tikal"],
  },
  {
    name: "Honduras",
    countryCode: "HN",
    aliases: [],
    cities: ["Tegucigalpa", "Roatán", "San Pedro Sula", "Copán"],
  },
  {
    name: "El Salvador",
    countryCode: "SV",
    aliases: [],
    cities: ["San Salvador", "Santa Ana", "El Tunco", "Suchitoto"],
  },
  {
    name: "Nicaragua",
    countryCode: "NI",
    aliases: [],
    cities: ["Managua", "Granada", "León", "San Juan del Sur", "Ometepe"],
  },
  {
    name: "Belice",
    countryCode: "BZ",
    aliases: ["belize"],
    cities: ["Belice City", "San Pedro", "Placencia", "Caye Caulker"],
  },
  {
    name: "China",
    countryCode: "CN",
    aliases: [],
    cities: ["Pekín", "Shanghái", "Hong Kong", "Cantón", "Shenzhen", "Xi'an", "Chengdu", "Guilin"],
  },
  {
    name: "Japón",
    countryCode: "JP",
    aliases: ["japan"],
    cities: ["Tokio", "Kioto", "Osaka", "Hiroshima", "Sapporo", "Nara", "Okinawa", "Fukuoka"],
  },
  {
    name: "Corea del Sur",
    countryCode: "KR",
    aliases: ["korea", "south korea"],
    cities: ["Seúl", "Busan", "Jeju", "Incheon", "Daegu"],
  },
  {
    name: "India",
    countryCode: "IN",
    aliases: [],
    cities: ["Nueva Delhi", "Mumbai", "Bangalore", "Jaipur", "Agra", "Goa", "Kerala", "Varanasi"],
  },
  {
    name: "Tailandia",
    countryCode: "TH",
    aliases: ["thailand"],
    cities: ["Bangkok", "Phuket", "Chiang Mai", "Krabi", "Pattaya", "Koh Samui"],
  },
  {
    name: "Vietnam",
    countryCode: "VN",
    aliases: [],
    cities: ["Hanói", "Ciudad Ho Chi Minh", "Da Nang", "Hoi An", "Halong", "Nha Trang"],
  },
  {
    name: "Indonesia",
    countryCode: "ID",
    aliases: [],
    cities: ["Bali", "Yakarta", "Surabaya", "Lombok", "Yogyakarta", "Komodo"],
  },
  {
    name: "Malasia",
    countryCode: "MY",
    aliases: ["malaysia"],
    cities: ["Kuala Lumpur", "Penang", "Langkawi", "Malaca", "Kota Kinabalu"],
  },
  {
    name: "Singapur",
    countryCode: "SG",
    aliases: ["singapore"],
    cities: ["Singapur"],
  },
  {
    name: "Filipinas",
    countryCode: "PH",
    aliases: ["philippines"],
    cities: ["Manila", "Cebú", "Palawan", "Boracay", "Bohol", "Davao"],
  },
  {
    name: "Emiratos Árabes Unidos",
    countryCode: "AE",
    aliases: ["uae", "dubai", "emiratos"],
    cities: ["Dubái", "Abu Dabi", "Sharjah", "Ajman"],
  },
  {
    name: "Arabia Saudita",
    countryCode: "SA",
    aliases: ["saudi arabia"],
    cities: ["Riad", "Yeda", "La Meca", "Medina", "Dammam"],
  },
  {
    name: "Qatar",
    countryCode: "QA",
    aliases: [],
    cities: ["Doha", "Al Wakrah", "Al Khor"],
  },
  {
    name: "Israel",
    countryCode: "IL",
    aliases: [],
    cities: ["Tel Aviv", "Jerusalén", "Haifa", "Eilat", "Safed"],
  },
  {
    name: "Jordania",
    countryCode: "JO",
    aliases: ["jordan"],
    cities: ["Amán", "Petra", "Aqaba", "Wadi Rum", "Jerash"],
  },
  {
    name: "Egipto",
    countryCode: "EG",
    aliases: ["egypt"],
    cities: ["El Cairo", "Luxor", "Aswan", "Alejandría", "Hurghada", "Sharm el-Sheij"],
  },
  {
    name: "Marruecos",
    countryCode: "MA",
    aliases: ["morocco"],
    cities: ["Marrakech", "Casablanca", "Fez", "Rabat", "Tánger", "Chefchaouen", "Merzouga"],
  },
  {
    name: "Túnez",
    countryCode: "TN",
    aliases: ["tunez", "tunisia"],
    cities: ["Túnez", "Sousse", "Djerba", "Kairouan", "Hammamet"],
  },
  {
    name: "Sudáfrica",
    countryCode: "ZA",
    aliases: ["south africa"],
    cities: ["Ciudad del Cabo", "Johannesburgo", "Durban", "Pretoria", "Kruger", "Stellenbosch"],
  },
  {
    name: "Kenia",
    countryCode: "KE",
    aliases: ["kenya"],
    cities: ["Nairobi", "Mombasa", "Masai Mara", "Malindi", "Lamu"],
  },
  {
    name: "Tanzania",
    countryCode: "TZ",
    aliases: [],
    cities: ["Dar es Salaam", "Zanzíbar", "Arusha", "Serengeti", "Kilimanjaro"],
  },
  {
    name: "Nigeria",
    countryCode: "NG",
    aliases: [],
    cities: ["Lagos", "Abuja", "Kano", "Port Harcourt"],
  },
  {
    name: "Ghana",
    countryCode: "GH",
    aliases: [],
    cities: ["Accra", "Kumasi", "Cape Coast", "Tamale"],
  },
  {
    name: "Etiopía",
    countryCode: "ET",
    aliases: ["ethiopia"],
    cities: ["Addis Abeba", "Lalibela", "Gondar", "Bahir Dar"],
  },
  {
    name: "Australia",
    countryCode: "AU",
    aliases: [],
    cities: ["Sídney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Cairns", "Gold Coast", "Canberra"],
  },
  {
    name: "Nueva Zelanda",
    countryCode: "NZ",
    aliases: ["new zealand"],
    cities: ["Auckland", "Wellington", "Queenstown", "Christchurch", "Rotorua", "Milford Sound"],
  },
  {
    name: "Fiyi",
    countryCode: "FJ",
    aliases: ["fiji"],
    cities: ["Nadi", "Suva", "Denarau", "Mamanuca"],
  },
];
