/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPackRouteImport } from './routes/api/pack'
import { Route as LayoutSuitcasesRouteImport } from './routes/_layout.suitcases'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutChecklistsRouteImport } from './routes/_layout.checklists'
import { Route as LayoutAssistantRouteImport } from './routes/_layout.assistant'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackRoute = ApiPackRouteImport.update({
  id: '/api/pack',
  path: '/api/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSuitcasesRoute = LayoutSuitcasesRouteImport.update({
  id: '/suitcases',
  path: '/suitcases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChecklistsRoute = LayoutChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssistantRoute = LayoutAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof LayoutAssistantRoute
  '/checklists': typeof LayoutChecklistsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/suitcases': typeof LayoutSuitcasesRoute
  '/api/pack': typeof ApiPackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof LayoutAssistantRoute
  '/checklists': typeof LayoutChecklistsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/suitcases': typeof LayoutSuitcasesRoute
  '/api/pack': typeof ApiPackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/assistant': typeof LayoutAssistantRoute
  '/_layout/checklists': typeof LayoutChecklistsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/suitcases': typeof LayoutSuitcasesRoute
  '/api/pack': typeof ApiPackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/checklists'
    | '/dashboard'
    | '/suitcases'
    | '/api/pack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/checklists'
    | '/dashboard'
    | '/suitcases'
    | '/api/pack'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/assistant'
    | '/_layout/checklists'
    | '/_layout/dashboard'
    | '/_layout/suitcases'
    | '/api/pack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiPackRoute: typeof ApiPackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pack': {
      id: '/api/pack'
      path: '/api/pack'
      fullPath: '/api/pack'
      preLoaderRoute: typeof ApiPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/suitcases': {
      id: '/_layout/suitcases'
      path: '/suitcases'
      fullPath: '/suitcases'
      preLoaderRoute: typeof LayoutSuitcasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checklists': {
      id: '/_layout/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof LayoutChecklistsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assistant': {
      id: '/_layout/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof LayoutAssistantRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAssistantRoute: typeof LayoutAssistantRoute
  LayoutChecklistsRoute: typeof LayoutChecklistsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutSuitcasesRoute: typeof LayoutSuitcasesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAssistantRoute: LayoutAssistantRoute,
  LayoutChecklistsRoute: LayoutChecklistsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutSuitcasesRoute: LayoutSuitcasesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ApiPackRoute: ApiPackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
